"""
Módulo de inicialização automática do banco de dados.
Cria as tabelas, tipos ENUM, índices e usuário admin padrão se não existirem.
"""
from src.config.database import get_db_cursor
from src.core.security import get_password_hash


def table_exists(cursor, table_name: str) -> bool:
    """Verifica se uma tabela existe no banco de dados."""
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = %s
        );
    """, (table_name,))
    return cursor.fetchone()[0]


def type_exists(cursor, type_name: str) -> bool:
    """Verifica se um tipo ENUM existe no banco de dados."""
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM pg_type 
            WHERE typname = %s
        );
    """, (type_name,))
    return cursor.fetchone()[0]


def index_exists(cursor, index_name: str) -> bool:
    """Verifica se um índice existe no banco de dados."""
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM pg_indexes 
            WHERE indexname = %s
        );
    """, (index_name,))
    return cursor.fetchone()[0]


def user_exists(cursor, username: str) -> bool:
    """Verifica se um usuário existe no banco de dados."""
    cursor.execute("SELECT EXISTS(SELECT 1 FROM usuarios WHERE username = %s);", (username,))
    return cursor.fetchone()[0]


def init_database():
    """
    Inicializa o banco de dados criando:
    - Tipos ENUM (user_role, task_status)
    - Tabelas (usuarios, tarefas)
    - Índices
    - Usuário admin padrão (se não existir)
    """
    print("\n" + "="*60)
    print("Inicializando banco de dados...")
    print("="*60)
    
    try:
        with get_db_cursor(commit=True) as cursor:
            # 1. Criar tipos ENUM
            print("\n[1/4] Verificando tipos ENUM...")
            
            if not type_exists(cursor, 'user_role'):
                print("   → Criando tipo ENUM 'user_role'...")
                cursor.execute("""
                    CREATE TYPE user_role AS ENUM (
                        'admin',
                        'gerencial',
                        'visualizacao'
                    );
                """)
                print("   ✓ Tipo 'user_role' criado com sucesso!")
            else:
                print("   ✓ Tipo 'user_role' já existe.")
            
            if not type_exists(cursor, 'task_status'):
                print("   → Criando tipo ENUM 'task_status'...")
                cursor.execute("""
                    CREATE TYPE task_status AS ENUM (
                        'pendente',
                        'em_andamento',
                        'em_revisao',
                        'concluida'
                    );
                """)
                print("   ✓ Tipo 'task_status' criado com sucesso!")
            else:
                print("   ✓ Tipo 'task_status' já existe.")
                # Verificar e adicionar valores faltantes se necessário
                def enum_value_exists_local(enum_type: str, enum_value: str) -> bool:
                    """Verifica se um valor existe em um tipo ENUM."""
                    cursor.execute("""
                        SELECT EXISTS (
                            SELECT 1 
                            FROM pg_enum 
                            WHERE enumlabel = %s 
                            AND enumtypid = (
                                SELECT oid 
                                FROM pg_type 
                                WHERE typname = %s
                            )
                        );
                    """, (enum_value, enum_type))
                    return cursor.fetchone()[0]
                
                if not enum_value_exists_local('task_status', 'em_andamento'):
                    print("   → Adicionando valor 'em_andamento'...")
                    cursor.execute("ALTER TYPE task_status ADD VALUE 'em_andamento';")
                    print("   ✓ Valor 'em_andamento' adicionado!")
                if not enum_value_exists_local('task_status', 'em_revisao'):
                    print("   → Adicionando valor 'em_revisao'...")
                    cursor.execute("ALTER TYPE task_status ADD VALUE 'em_revisao';")
                    print("   ✓ Valor 'em_revisao' adicionado!")
            
            # 2. Criar tabela de usuários
            print("\n[2/4] Verificando tabela 'usuarios'...")
            if not table_exists(cursor, 'usuarios'):
                print("   → Criando tabela 'usuarios'...")
                cursor.execute("""
                    CREATE TABLE usuarios (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username TEXT UNIQUE NOT NULL,
                        email TEXT UNIQUE NOT NULL,
                        hashed_password TEXT NOT NULL,
                        role user_role NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    );
                """)
                print("   ✓ Tabela 'usuarios' criada com sucesso!")
            else:
                print("   ✓ Tabela 'usuarios' já existe.")
            
            # 3. Criar tabela de tarefas
            print("\n[3/4] Verificando tabela 'tarefas'...")
            if not table_exists(cursor, 'tarefas'):
                print("   → Criando tabela 'tarefas'...")
                cursor.execute("""
                    CREATE TABLE tarefas (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        titulo TEXT NOT NULL,
                        descricao TEXT,
                        status task_status NOT NULL DEFAULT 'pendente',
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                        owner_id INT NOT NULL,
                        CONSTRAINT fk_owner
                            FOREIGN KEY(owner_id) 
                            REFERENCES usuarios(id)
                            ON DELETE CASCADE
                    );
                """)
                print("   ✓ Tabela 'tarefas' criada com sucesso!")
            else:
                print("   ✓ Tabela 'tarefas' já existe.")
            
            # 4. Criar índices
            print("\n[4/4] Verificando índices...")
            if not index_exists(cursor, 'idx_tarefas_owner_id'):
                print("   → Criando índice 'idx_tarefas_owner_id'...")
                cursor.execute("""
                    CREATE INDEX idx_tarefas_owner_id ON tarefas(owner_id);
                """)
                print("   ✓ Índice 'idx_tarefas_owner_id' criado com sucesso!")
            else:
                print("   ✓ Índice 'idx_tarefas_owner_id' já existe.")
            
            # 5. Criar usuários padrão (se não existirem)
            print("\n[EXTRA] Verificando usuários padrão...")
            
            # Usuário Admin
            if not user_exists(cursor, 'admin'):
                print("   → Criando usuário admin...")
                admin_password = 'admin123'
                hashed_password = get_password_hash(admin_password)
                cursor.execute("""
                    INSERT INTO usuarios (username, email, hashed_password, role) 
                    VALUES (%s, %s, %s, %s);
                """, ('admin', 'admin@example.com', hashed_password, 'admin'))
                print("   ✓ Usuário admin criado com sucesso!")
                print(f"      Username: admin | Senha: admin123 | Role: admin")
            else:
                print("   ✓ Usuário admin já existe.")
            
            # Usuário Gerencial
            if not user_exists(cursor, 'gerencial'):
                print("   → Criando usuário gerencial...")
                gerencial_password = 'gerencial123'
                hashed_password = get_password_hash(gerencial_password)
                cursor.execute("""
                    INSERT INTO usuarios (username, email, hashed_password, role) 
                    VALUES (%s, %s, %s, %s);
                """, ('gerencial', 'gerencial@example.com', hashed_password, 'gerencial'))
                print("   ✓ Usuário gerencial criado com sucesso!")
                print(f"      Username: gerencial | Senha: gerencial123 | Role: gerencial")
            else:
                print("   ✓ Usuário gerencial já existe.")
            
            # Usuário Visualização
            if not user_exists(cursor, 'usuario'):
                print("   → Criando usuário visualização...")
                usuario_password = 'usuario123'
                hashed_password = get_password_hash(usuario_password)
                cursor.execute("""
                    INSERT INTO usuarios (username, email, hashed_password, role) 
                    VALUES (%s, %s, %s, %s);
                """, ('usuario', 'usuario@example.com', hashed_password, 'visualizacao'))
                print("   ✓ Usuário visualização criado com sucesso!")
                print(f"      Username: usuario | Senha: usuario123 | Role: visualizacao")
            else:
                print("   ✓ Usuário visualização já existe.")
            
            print("\n" + "="*60)
            print("✓ Inicialização do banco de dados concluída com sucesso!")
            print("="*60 + "\n")
            
    except Exception as e:
        print(f"\n❌ ERRO ao inicializar banco de dados: {e}")
        print("Verifique se o banco de dados está rodando e se as credenciais estão corretas.")
        raise


if __name__ == "__main__":
    # Permite executar o script diretamente para testar
    init_database()

